### ISSUE TITLE
Setting Snapping to Measurement Tools Help

### ISSUE THREAD

**Issue by elephantcatdog** [PDFTron/webviewer-ui#621] opened 2020-05-21 17:58 UTC
Hello,

I am trying to set snapping to measurement tools conditionally based on user input. I've done it very similarly to the setup in the[ measurement demo](https://www.pdftron.com/webviewer/demo/measurement-tools).
Demo
![image](https://user-images.githubusercontent.com/37936169/82577285-5bea6b80-9b50-11ea-8d21-1e2b5509ae5f.png)
Mine (in MeasurementOption.js)
![image](https://user-images.githubusercontent.com/37936169/82577424-97853580-9b50-11ea-8799-7c5c182fc18a.png)
I am getting the measurement tools the way it's done in setToolStyles.js.

However, setting the snap mode on the measurement tools results in several errors. In-progress annotations are invisible, and the distance measurement tool does not work at all. The video below shows the problem. The created annotations appear in the right panel. The snapping distance annotation is never created, unlike the snapping perimeter and area annotations.
![floorplanpdf-Google-Chrome-2020](https://user-images.githubusercontent.com/37936169/82589957-80e7da00-9b62-11ea-9501-0f65c26e4bdd.gif)

What am I doing incorrectly? Is there a setting I'm missing?
Thanks for the help.

**Comment by ZhijieZhang** [comment] 2020-05-21 21:23
Hmm I didn't notice anything wrong actually. I don't think calling `onStyleChange` with `Snapping` will do anything, but this shouldn't cause the issue that you see in the gif. Maybe you can try removing it and see if the issue is resolved?

To help you progress further I've pushed a branch https://github.com/PDFTron/webviewer-ui/tree/feat/measurement-snap to Github, in which I added a checkbox to toggle snapping.

This is what I see using the branch:
![snap](https://user-images.githubusercontent.com/25110092/82607860-7b908c80-9b6e-11ea-809f-67aa3f579dc8.gif)

Can you try it out and see how it goes? Thanks!

**Comment by ZhijieZhang** [comment] 2020-05-27 20:09
Any chances you are testing snapping with a XOD document? I noticed the behaviour in your gif if a XOD document is loaded. I don't think XOD documents have snapping, so you might want to unmount the toggle box for them.

**Comment by elephantcatdog** [comment] 2020-05-29 16:04
Hi @ZhijieZhang 
Thanks for looking into my problem. I downloaded this branch and followed the startup directions in the ReadMe, but there is no measurement tools button. It looks like the regular demo. I haven't changed anything; is there something I should change or do?

**Comment by ZhijieZhang** [comment] 2020-06-02 22:26
Hi there, sorry for the delay in the response!

If you are running the UI standalone, then you can open the console and then call `readerControl.enableMeasurement()`;

Alternatively you can also just remove the following lines for quick testing:
https://github.com/PDFTron/webviewer-ui/blob/bd8e91fe635c80183bfe8a19ef1ef1ac25a5d6aa/src/helpers/setDefaultDisabledElements.js#L42-L45

**Comment by ZhijieZhang** [comment] 2020-06-08 16:17
I'm going to close this issue for now because I think the information above should be enough to help you to progress. But just as usual, free feel to reopen it and discuss if you have more questions. Thanks!

**Closed by ZhijieZhang** 2020-06-08 16:17 UTC
