### ISSUE TITLE
Signature is placed to the left of the cursor

### ISSUE THREAD

**Issue by elephantcatdog** [PDFTron/webviewer-ui#536] opened 2020-03-13 21:33 UTC
Version: 6.1.1
Browser: Chrome 80.0.39878.132

Steps to Reproduce:
1. Open https://www.pdftron.com/webviewer/demo/ in Chrome
2. Upload [abc.pdf](https://github.com/PDFTron/webviewer-ui/files/4331620/abc.pdf)
3. Create and place a signature on the right quarter of the screen.

![PDFTron-WebViewer-Demo-JavaScrip (1)](https://user-images.githubusercontent.com/37936169/76660007-ee193680-6545-11ea-9f9c-3921ad7e188e.gif)

When placing signatures on the right quarter of the screen (approximately from the right edge of the image on the first page) on any page in the PDF the signature is moved to the left of the cursor. This doesn't occur on the left side of the screen, nor for every PDF.

**Comment by ZhijieZhang** [comment] 2020-03-16 15:11
Thanks for bringing this up with detailed information. I'm able to reproduce the issue with the file on my end.

I'm going to take a look at this issue. My feeling is that when the signature is added at the right edge of the document, we somehow think that's actually out the page boundary, and relocate its position. I will let you know once I have more information.

**Comment by ZhijieZhang** [comment] 2020-03-16 17:26
I attempted to make a fix and included it in this custom build  https://pdftron.s3.amazonaws.com/custom/ID-zJWLuhTffd3c/WebViewer/WebViewer-6.2.0-signature-position-rotation.zip.

Can you try the build and see if the issue is resolved? The fix is being reviewed, and will be included in the official release shortly.

**Comment by elephantcatdog** [comment] 2020-03-16 19:32
That did fix it, thank you!

**Closed** 2020-03-18 23:20 UTC
