### ISSUE TITLE
Rectangle Regular/Cloudy not visible in iPhone and maybe iPad? in Landscape mode

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#561] opened 2020-04-07 01:16 UTC
WV: 6.2.2
iOS: 13.2.2

Open document in landscape in said device/OS.
Attempt to create Rectangle annotation.
Unable to see Regular/Cloudy selection of additional menu.

Selection is visible in Portrait.

See potato screenshot of a video.

**Bad -**
![image](https://user-images.githubusercontent.com/4165721/78619554-3e34a180-7843-11ea-8a9a-804f457ac603.png)

**Good -** 
![image](https://user-images.githubusercontent.com/4165721/78619600-55738f00-7843-11ea-9a99-44f4b23146fa.png)

**Comment by ZhijieZhang** [comment] 2020-04-09 02:54
Thanks for bringing this up. Looks like in the landscape mode we should at least make the style picker to be scrollable so that regular or cloudy style can be used.

I will take a look at this, and will let you know once I have more information!

**Comment by ZhijieZhang** [comment] 2020-04-16 19:39
Hi, this issue should be fixed in the latest nightly build. Can you give it a shot and see if the issue is resolved? Thanks.

**Comment by henry-chris** [comment] 2020-04-16 20:46
Thanks.  I will likely wait until 1-2 other issues are in the nightly and test them all out at once.

**Closed** 2020-04-25 22:09 UTC
