### ISSUE TITLE
Annotation edit popup occludes stickynotes

### ISSUE THREAD

**Issue by rbarrpdftron** [PDFTron/webviewer-ui#313] opened 2019-07-19 22:02 UTC
Open PDF where page 1 has a non-zero rotation entry
Add sticky note
Click on sticky note
The pop up menu completely covers the annotation, so you cannot move the sticky note.

**Comment by ZhijieZhang** [comment] 2019-07-22 23:59
The issue is fixed in the above commit and will be included in the 5.2 release.

**Closed by ZhijieZhang** 2019-07-22 23:59 UTC
