### ISSUE TITLE
Sorting annotations by Type may cause errors when Subject is null

### ISSUE THREAD

**Issue by tporadowski** [PDFTron/webviewer-ui#914] opened 2021-04-28 19:30 UTC
Hi,

I happened to be working with a PDF file (version 1.4) that had 3 annotations, where each of them after importing had `Subject` set to `null`. Acrobat didn't complain that the file is corrupted, and as far as I could see in PDF specification - that attribute is optional (added in version 1.5?). This leads to an error when user is trying to sort annotations in `NotesPanel` by "Type", which leads to whole UI going blank because of this error (I uploaded this file for testing to PDFTron demo):

![obraz](https://user-images.githubusercontent.com/6212622/116460025-d7779100-a866-11eb-90cd-f971b6c5297f.png)

It is caused by this part which assumes that `Subject` is always there:
https://github.com/PDFTron/webviewer-ui/blob/3b7901d13b48aec3236dd872a8c072670aeb31cb/src/constants/sortStrategies.js#L129

I don't know how this PDF was created, but I'm attaching it to reproduce the issue (I've changed the owner of annotations to my name). Just load it in WebViewer, open "Notes panel" and sort by "Type".
[annotations_without_subject.pdf](https://github.com/PDFTron/webviewer-ui/files/6394303/annotations_without_subject.pdf)

**Comment by tporadowski** [comment] 2021-04-29 08:21
I have some update related to origin of that PDF - it was processed by a middleware application that (among other actions) takes some annotations (sticky notes) from original XFDF, copies over most of attributes (but not "subject") and saves them in final PDF. Thus we get a PDF with annotations that have no "Subject" property after loading such a document to WebViewer.

**Comment by mparizeau-pdftron** [comment] 2021-05-03 19:02
Thanks for the report! We're able to reproduce and currently working on fixing this. We'll let you know when the fix is merged in.

**Comment by mparizeau-pdftron** [comment] 2021-05-15 00:18
It looks like the fix for this has been merged into our 7.3 branch now. Can you test out our latest stable nightly build to confirm it's working for you https://www.pdftron.com/documentation/web/faq/webviewer-nightly-build/

**Comment by bollain** [comment] 2022-02-15 01:36
Closing due to inactivity. Feel free to re-open it if this is still a problem.

**Closed by bollain** 2022-02-15 01:36 UTC
