### ISSUE TITLE
Demo viewer crashes when selecting and typing at the same time

### ISSUE THREAD

**Issue by creage** [PDFTron/webviewer-ui#870] opened 2020-08-31 11:08 UTC
Trying to mark a part of PDF and type something crashes the viewer. Console shows exceptions.

1. Open Demo page at https://www.pdftron.com/webviewer/demo/
2. Resize window so no additional panes are visible
3. Enable select tool
4. Select some area and try to type at the same time.

Viewer crashes.

Please see attached zip with mp4 recorded for details.

[PDFTronDemo_typing.zip](https://github.com/PDFTron/webviewer-ui/files/5149940/PDFTronDemo_typing.zip)

**Comment by creage** [comment] 2020-09-07 13:07
@khein-pdftron did you mates had a chance to look at this issue?

**Comment by ZhijieZhang** [comment] 2020-09-08 18:35
Sorry for the delay in the response! It looks like this issue has been fixed in the nightly build. Can you give https://www.pdftron.com/nightly/#stable/2020-09-08/ a try and see how it goes?

**Comment by creage** [comment] 2020-09-09 06:14
@ZhijieZhang can we install nightly builds using npm? As we cannot test other deployments due to our CI/CD pipeline setup.

**Comment by ZhijieZhang** [comment] 2020-09-09 20:46
Unfortunately nightly builds are not available on npm yet, which is what we are currently working on.

Did you get a chance to try the nightly build on your end just to see if the issue is fixed? If it's all good then the fix will be available in the next patch release of 7.0. 

Currently we don't have a timeline for this since we are working on the 7.1 release, but if it's an urgent fix to you then we can schedule a patch release soon. Let me know.

**Comment by creage** [comment] 2020-09-10 07:06
Once again - we cannot just download and replace Webviewer sources due to our build pipeline, we need such sources to be available on NPM registry. Changing this approach will require hell a lot of work, which I'm not sure we should do just to verify if the issue we report is fixed.

**Comment by ZhijieZhang** [comment] 2020-09-10 17:28
Hey sorry for not making myself clear in the previous response.

I didn't mean to ask you to test the nightly build with your application since you mentioned it doesn't work with your setup. What I meant is to download the package and then just test the sample inside the package.

You can totally skip this because I've verified on my end, but I was just wanting to be secure.

**Comment by creage** [comment] 2020-09-11 08:03
@ZhijieZhang I was not aware that you can actually run nightly build without installing it. But we succeed in starting it locally and our QA confirms that issue is not reproducible anymore on the version you provided.

So, what is the procedure to get that fix available on npm?

**Comment by ZhijieZhang** [comment] 2020-09-21 17:35
Sorry for the delay in the reply!

We just managed to make WebViewer nightly builds available on `npm`. Here's the FAQ https://www.pdftron.com/documentation/web/faq/webviewer-nightly-build/ that talks about how you can install it.

Can you give it a try and see if it resolves the issue on your end?

**Comment by ZhijieZhang** [comment] 2021-01-13 20:18
Closing due to inactivity.

**Closed by ZhijieZhang** 2021-01-13 20:18 UTC
