### ISSUE TITLE
Coloring Annotation Tools Icons according to selected color

### ISSUE THREAD

**Issue by timoSpr** [PDFTron/webviewer-ui#466] opened 2020-01-09 15:42 UTC
STR: 
- select an annotation tool in the header: AnnotationCreateTextUnderline, AnnotationCreateTextSquiggly or AnnotationCreateTextStrikeout
- select a new color for the tool

ER: 
- the icon of the toolButton is reflecting the selected color

AR: 
- the icons remain white when unselected. Only when they are selected do they reflect the color. 
- in Contrast, the AnnotationCreateTextHighlight always reflects the selected color, no matter if selected or not.

PDFTron v5.2, Google Chrome Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by ZhijieZhang** [comment] 2020-01-10 20:16
Thanks for bringing this up!

I see what you mean and I think this is actually the expected behaviours in the current UI design. The reason why we choose to always show the color for the highlight and freehand tool buttons is because they have 4 presets while other tool buttons don't.

I'm a little hesitated to just change other tool buttons to always show the color because this will result in a quite different user experience than what they have now.

So for now, to change the button colors you need to modify the UI source code. The specific location you'd want to modify is https://github.com/PDFTron/webviewer-ui/blob/6.0/src/redux/initialState.js#L136.

For example, if you want the underline tool to always show the color, change
```javascript
AnnotationCreateTextUnderline: { dataElement: 'underlineToolButton', title: 'annotation.underline', img: 'ic_annotation_underline_black_24px', group: 'textTools', showColor: 'active' },
```
to
```javascript
AnnotationCreateTextUnderline: { dataElement: 'underlineToolButton', title: 'annotation.underline', img: 'ic_annotation_underline_black_24px', group: 'textTools', showColor: 'always' },
```

Please refer to this guide https://www.pdftron.com/documentation/web/guides/advanced-customization/ which talked about how you can modify the UI source code and then use the modified one in your own project.

Let me know if you have questions. Have a nice day!

**Comment by ZhijieZhang** [comment] 2020-01-16 22:39
I will close this issue for now because I believe the original question is answered. However I could overlook somethings so please feel free to reopen it and discuss it further if you'd like. Thanks and have a nice day!

**Closed** 2020-01-16 22:39 UTC
