### ISSUE TITLE
Documentation incorrect for 6.0 upgrade

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#534] opened 2020-03-11 20:01 UTC
// Version 6.0 and after
docViewer.on('zoomUpdated', zoom => {
  ...
});
annotManager.on('annotationChanged', (annotations, action, **{ imported }**) => {
  if (imported) {
    ...
  }
});

Bolded text should be   { imported, isUndoRedo }.  As of v6.1.1.  Otherwise it throws an error.

**Comment by ZhijieZhang** [comment] 2020-03-13 17:43
You are right that the third argument of the event callback is an object that contains `imported` and `isUndoRedo`. I believe that the reason why we didn't show the `isUndoRedo` property when destructuring the object is that it's not being used in the callback.

Just want to confirm that this is not an issue in 6.0, but only an issue in 6.1.x? It could be a bit strange if this is the case since we didn't change the function signatures for the callback after 6.0. Do you mind showing an example where an error is thrown?

**Comment by henry-chris** [comment] 2020-03-13 19:43
I never tried 6.0.

The error I was getting was -> 

TypeError: Cannot read property 'AU' of undefined
at ...  CoreControls.js:286

---
TypeError: Cannot read property 'imported' of undefined
at ...  (our custom file where we listen for annotation events for real time updating)

changing the `{ imported }` to `{ imported, isUndoRedo }` fixed it even though it's not being used.

The error doesn't seem to be in your code, just in the documentation. So when anyone tries to actually implement it they'll get an error and will need to debug it to figure out what's happening.

**Comment by ZhijieZhang** [comment] 2020-03-16 14:52
Thanks for the elaboration. Based on the error message, I'm wondering if you are manually triggering an `annotationChanged` event in your real time updating file? If this is the case then in 6.x you would need to include the info argument. For example:

```javascript
const info = {
  imported: false, // optional
  inUndoRedo: false // optional
}

annotManager.trigger('annotationChanged', [annotations, 'add', info]); // info needs to be an object at least
```

I don't really think that not destructuring `isUndoReo` when **listening** `annotationChanged` event will throw an error, if you are not using it in the event callback. But I could be miss something, if this is the case you are encountering, please share a code snippet. Thanks!

**Comment by henry-chris** [comment] 2020-03-20 08:59
We are listening for the event.  

The docs **specifically** destructure an object that looks like `{ imported }`.  While I could listen for an `info` object it kind of defeats the purpose of looking at the docs no?  And even then it still hides the fact that `isUndoRedo` exists since it's not documented anywhere.

Basically, what I'm saying is if you go by the docs and web page it will be implemented wrong.  This will happen to many developers also trying to listen for events.  To mitigate all this time wasted looking at docs and debugging, if you just change your docs and/or put object in types.d.ts it should be much easier.  

It does look like the new types.d.ts has the correct parameters for each annotation event.  However when listening for 'AnnotationChanged' it's almost impossible to know which events trigger it unless you do an exhaustive search of the file and connect the dots.

Most of the comments in types.d.ts for` annotManager.on('annotationChanged',...` also do not depict the `info` object.

Here is the specific page which talks about upgrading to V6 and causes the error - https://www.pdftron.com/documentation/web/get-started/migrating-to-v6/

I'm really just trying to make it easier for others so they don't have the same problems I had.

Here's another thing that can be fixed I think:
![image](https://user-images.githubusercontent.com/4165721/77149002-ae2ee380-6a5e-11ea-9816-17d42510a4cc.png)

This function actually takes an options object that can handle more than just 'withCredentials'.  For example I spent a good amount of time figuring out that it can take custom headers.  Like so:

`    const response = await window.PDFNet.PDFDoc.createFromURL(accessUrl, {      
          customHeaders: {
            Authorization: await this._authnService.getAuthToken()
          }
    });  `

Maybe this isn't the correct place to make these issues since it is specifically the UI. I can make them elsewhere if you'd like, or stop altogether.

Just let me know.

**Comment by ZhijieZhang** [comment] 2020-03-20 16:03
Thanks for the reply. I will make a change to our docs regarding the `info` argument in the `annotationChanged` callback to reduce confusions. Regarding the `options` in `createFromURL`, I would need to talk to my colleague since it's full apis related.

> changing the { imported } to { imported, isUndoRedo } fixed it even though it's not being used.

Regarding this, I'm still having some trouble to reproduce the issue where only having `{ imported }` when listening the event will throw an error. If you want to show me an example where I can reproduce, that'd be great.

**Comment by henry-chris** [comment] 2020-03-20 18:43
Well, you actually need to try to use the `imported` variable.

**Comment by ZhijieZhang** [comment] 2020-03-23 16:21
I tried to modify the `viewing.js` sample in the downloaded package to the following, but still wasn't able to reproduce the issue :(.

```javascript
WebViewer(
  {
    path: '../../../lib',
    initialDoc: 'https://pdftron.s3.amazonaws.com/downloads/pl/demo-annotated.pdf',
  },
  document.getElementById('viewer')
).then(function(instance) {
  instance.annotManager.on('annotationChanged', (annotations, action, { imported }) => {
    console.log(imported);
  });

  document.getElementById('select').onchange = function(e) {
    instance.loadDocument(e.target.value);
  };

  document.getElementById('file-picker').onchange = function(e) {
    var file = e.target.files[0];
    if (file) {
      instance.loadDocument(file);
    }
  };

  document.getElementById('url-form').onsubmit = function(e) {
    e.preventDefault();
    instance.loadDocument(document.getElementById('url').value);
  };
});
```

The usage of `imported` is very minimal(a console log) in the code snippet, which makes it unlikely to throw an error. It'd be helpful if you can provide us with a code snippet that shows the error.

**Comment by henry-chris** [comment] 2020-03-24 11:10
I'm unsure, then.  That's the exact code I was using and I've given you the 2 errors previously.  Could be a transpilation issue on my side as we use Typescript for the files this code exists within.

You function is correct (in your example).  It's just that in my code, it throws the errors..

Feel free to close then.  At least documentation changes may be worthwhile. 

EDIT: Ported code to JS file, no error is thrown.  We use babel-loader to transpile typescript so there may be something in there that is different.  I haven't looked at production files to verify.

**Comment by ZhijieZhang** [comment] 2020-03-30 18:19
Thanks for confirming. I've updated the documentation and the migration guide to mention `isUndoRedo`. The changes should be available very soon, so I will close this ticket for now.

Let me know if you have any further questions. Thanks!

**Closed by ZhijieZhang** 2020-03-30 18:19 UTC
