### ISSUE TITLE
 hot update was not successful [Bug] 

### ISSUE THREAD

**Issue by rahul05ranjan** [PDFTron/webviewer-ui#945] opened 2022-01-11 17:43 UTC
**WebViewer version**
The latest one

**Steps to reproduce**

I followed the readme.md installation steps.
And I got below error.

`hot update was not successful collapseRetry
(1/1)
hot update failed for module "./src/components/App/App.js". Last file processed: "".

ERROR in ./src/index.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js??postcss!./node_modules/sass-loader/dist/cjs.js!./src/index.scss)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (/var/www/html/node/learn/webviewer-ui/node_modules/postcss-loader/dist/index.js:40:24)
ERROR in ./src/components/FilePickerHandler/FilePickerHandler.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js??postcss!./node_modules/sass-loader/dist/cjs.js!./src/components/FilePickerHandler/FilePickerHandler.scss)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (/var/www/html/node/learn/webviewer-ui/node_modules/postcss-loader/dist/index.js:40:24)
ERROR in ./src/components/Accessibility/Accessibility.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js??postcss!./node_modules/sass-loader/dist/cjs.js!./src/components/Accessibility/Accessibility.scss)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (/var/www/html/node/learn/webviewer-ui/node_modules/postcss-loader/dist/index.js:40:24)
ERROR in ./src/components/Header/Header.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js??postcss!./node_modules/sass-loader/dist/cjs.js!./src/components/Header/Header.scss)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (/var/www/html/node/learn/webviewer-ui/node_modules/postcss-loader/dist/index.js:40:24)
ERROR in ./src/components/DocumentContainer/DocumentContainer.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js??postcss!./node_modules/sass-loader/dist/cjs.js!./src/components/DocumentContainer/DocumentContainer.scss)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (/var/www/html/node/learn/webviewer-ui/node_modules/postcss-loader/dist/index.js:40:24)
ERROR in ./src/components/Choice/Choice.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js??postcss!./node_modules/sass-loader/dist/cjs.js!./src/components/Choice/Choice.scss)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (/var/www/html/node/learn/webviewer-ui/node_modules/postcss-loader/dist/index.js:40:24)`

**Comment by bollain** [comment] 2022-01-11 20:04
Hi @rahul05ranjan,

I am not able to reproduce this issue. Following our install steps I'm able to install all node modules and run the app with `npm start`.

Can you clarify the reproduction steps for this, and at which step it happens? Have you updated any of the dependencies? A quick search leads me to this same error being discussed in relation to a specific version of `sass-loader`:
https://stackoverflow.com/questions/66082397/typeerror-this-getoptions-is-not-a-function

**Comment by bollain** [comment] 2022-01-21 18:48
Closing as no repro steps provided, please feel free to re-open if you are able to provide more info.

**Closed by bollain** 2022-01-21 18:48 UTC

**Comment by euangordon** [comment] 2022-06-15 14:26
@rahul05ranjan Did you ever get this to work? I have exactly the same issue. Raised a ticked with my information
