### ISSUE TITLE
7.1.2 CSS preventing Searchpanel from closing?

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#883] opened 2020-10-14 20:28 UTC
1. Search panel initial size is 293 px.  Nothing gives it a smaller width or display: none that I can see.
2. Padding and the search button prevent width: 0 from working.

Am I missing something?  Are you all not seeing this and we just have a CSS conflict that I cannot find?

End result for our app after merging 7.1.2 is that the search panel is opened from the start and will never close.  The CSS class says it's 'closed' though, but the inline style has it at '293'.

Are we sticking with a width change to do the animation (open/close) or are we going back to a CSS transition of some sort?

**Comment by ZhijieZhang** [comment] 2020-10-30 19:57
Sorry for the delay in the response. This slips through my list.

Is this still an issue on your end? I tried on the webviewer demo but couldn't reproduce it.

If you would like us to take a further look then can you share the link to the forked repo?

In the future, to best ensure your questions go to the correct team member, and are tracked properly, please use this web form to submit tickets https://www.pdftron.com/form/request/. Thanks for your understanding!

**Comment by ZhijieZhang** [comment] 2020-11-02 20:30
I just synced with the team and we feel like the issue you are describing here is resolved in this commit https://github.com/PDFTron/webviewer-ui/commit/e0726ee1dadaa18ec2e01d5e950d8a6f91c068e8. The commit is currently only in the master branch, so it will be part of the next official release.

**Comment by ZhijieZhang** [comment] 2021-01-13 20:12
I believe this is no longer the issue as the CSS library is removed in 7.2. I'm closing this issue for now. Feel free to reopen this issue for further questions.

**Closed by ZhijieZhang** 2021-01-13 20:12 UTC
