### ISSUE TITLE
Resizing LeftPanel makes WebViewer overflow when opening RightPanel

### ISSUE THREAD

**Issue by Sjeijoet** [PDFTron/webviewer-ui#882] opened 2020-10-06 09:04 UTC
Browser: Google Chrome Version 85.0.4183.121 (64-bit)
WebViewer: Version 7.1.0

This is reproducable in the online demo:
1. Open the LeftPanel.
2. Resize the LeftPanel.
3. Open the RightPanel (Search or comments).
4. The viewer jumps to the left and is now partially invisible.

![webviewer](https://user-images.githubusercontent.com/2961989/95181478-a39e2680-07c3-11eb-9715-cd60e5603984.png)

**Comment by ZhijieZhang** [comment] 2020-10-13 20:04
Hey sorry for the delay in the reply!

I believe one of my colleagues is working on this issue, and I will let you know once we have more information. Thanks for your patience!

**Comment by ZhijieZhang** [comment] 2021-01-13 20:15
The online demo has been updated to 7.2 and I can't seem to reproduce the issue anymore.

Could you try the latest 7.2 build and see if the issue is resolved on your end? I'm closing the issue for now. Feel free to reopen it for any related issues.

**Closed by ZhijieZhang** 2021-01-13 20:15 UTC
