### ISSUE TITLE
[Bug] unable to call `setFitMode(FitWidth)` in the `documentLoaded` event listener 

### ISSUE THREAD

**Issue by chenghongyao** [PDFTron/webviewer-ui#940] opened 2021-11-30 08:25 UTC
Hello, thanks for the project.

I'm trying to set the `FitMode` to `FitWidth` in a config file every time the document is loaded, but when the document is loaded, it seems to the `FitMode`  is set to `FitWidth` and then suddenly turn back to `FitPage`.

**WebViewer version**
8.0.0
**The current behavior**
When i open a pdf file, the `FitMode` is set to `FitWidth` and then set to `FitPage` immediately.
**The expected behavior**
The `FitMode` should keep in `FitWidth`.
**Steps to reproduce**
1. clone the electorn demo: https://github.com/PDFTron/webviewer-electron-sample
2. create a file call `config.js` in `public` folder, and the content is 
```js
window.addEventListener('documentLoaded', () => {
	instance.UI.setFitMode(instance.UI.FitMode.FitWidth)
});
```
3. add this file  to to the parameter of WebViewer
```js
WebViewer(
  {
    path: "../public/lib",
    initialDoc: "../public/files/webviewer-demo-annotated.pdf",
    config: "../public/config.js",
  },
  viewerElement
).then(...)

```
4. start the application , and click `Open File` button to open a new file.

**Comment by bollain** [comment] 2021-12-02 19:21
Hi @chenghongyao,

Are you able to update to the latest version of WebViewer? There was a bug with config files that has been fixed since 8.0 was released. I am not able to reproduce this issue.

https://www.pdftron.com/documentation/web/download

**Comment by furdakov** [comment] 2021-12-21 14:29
Experiencing this issue for files with more than ~500 pages in 8.0.1.
I'm able to set fit mode to FitWidth after document is loaded, but after ~500ms viewer automatically set fit mode to FitPage

**Comment by xmhealth** [comment] 2022-02-06 14:16
+1

**Comment by bollain** [comment] 2022-02-07 23:09
I tried to reproduce this issue but are still not able to. Here are my steps:

1) Initialize WebViewer with the following code:
```
Webviewer({
  initialDoc: 'https://pdftron.s3.amazonaws.com/downloads/pl/webviewer-demo.pdf',
  path: '/lib',
}, document.getElementById('viewer')).then(instance => {
  const { documentViewer } = instance.Core;
  documentViewer.addEventListener('documentLoaded', () => {
    instance.UI.setFitMode(instance.UI.FitMode.FitWidth)
  })
});
```

2) Load document with > 500 pages (I used the tax act doc in our demo https://www.pdftron.com/webviewer/demo/)

Doc loads as expected and I dont see it switch out of FitWidth.

Tested using 8.2 from our nightly builds for February 7th:
https://www.pdftron.com/nightly/#stable/

Can you confirm reproduction steps and versions being used to replicate this bug?

**Comment by xmhealth** [comment] 2022-02-08 06:53
It workes for me. Thank you. @bollain 

My old code does not work:
`instance.UI.loadDocument(url, { filename: 'doc.pdf' });
 instance.UI.setFitMode(instance.UI.FitMode.FitWidth); //does not work when load second document
`

**Comment by furdakov** [comment] 2022-02-08 08:24
@bollain 
I've created little angular project to reproduce this issue with latest nightly build of @pdftron/webviewer
https://github.com/furdakov/webviewer-bug-demo
clone repo
npm install
ng serve

observe UI behavior and console logs.

**Comment by chenghongyao** [comment] 2022-02-08 15:10
Sorry for the late reply. 

I still can't make it work. It happens only for some pdf files. Try [this](https://arxiv.org/pdf/2001.01439v1.pdf).

**Comment by bollain** [comment] 2022-02-08 19:56
Thanks for that sample @furdakov. This is not a bug in WebViewer, but the result of an open Action embedded in your sample document. WebViewer includes the action as part of the XFDF data and parses this asynchronously so there might be a bit of a delay before the open action is triggered. For this particular case, the action triggers the FitMode to be FitPage.

To work around this what you can do is ignore any GoTo open actions that are triggered on the document. You can add the following code:
```
const { Actions, docViewer } = instance;
const onTriggered = Actions.GoTo.prototype.onTriggered;
Actions.GoTo.prototype.onTriggered = function(target, event) {
  if (target === docViewer.getDocument() && [event.name](http://event.name/) === 'Open') {
    return;
  }

  onTriggered.apply(this, arguments);
};
```

**Comment by bollain** [comment] 2022-02-08 19:57
@chenghongyao if this only happens for certain PDFs, then it's very likely it is also due to an open action. See my previous comment for a way to get around these.

**Comment by furdakov** [comment] 2022-02-08 21:07
@bollain Ok. Now I'm understand. Thank you for help with this!

**Comment by bollain** [comment] 2022-02-08 21:12
Closing issue now but feel free to re-open if you have further questions.

**Closed by bollain** 2022-02-08 21:12 UTC

**Comment by xmhealth** [comment] 2023-12-12 01:36
@pallaviMN I used @react-pdf-viewer insteaded.
