### ISSUE TITLE
Resizing grip in the side panel

### ISSUE THREAD

**Issue by Camo30** [PDFTron/webviewer-ui#403] opened 2019-11-07 12:44 UTC
Version: 5.2.4.72582 (not fixed in 5.2.7.72921)
Browser: Firefox 70.0.1

Steps to reproduce:

1. Open https://www.pdftron.com/webviewer/demo/ in the mobile view (IPhone 6/7/8)
1. Open side panel (e.g. thumbnail view)
1. Move the cursor over the thumbnails, there is some space where the cursor changes from the default cursor to a resizing cursor

Expected behaviour:
The resizing grip (cursor) should not be there, because there is nothing to resize. Please see picture below

![2019-11-07 13_28_33-PDFTron WebViewer Demo](https://user-images.githubusercontent.com/33700436/68389951-818bc680-0164-11ea-8e6e-8a199702fa90.jpg)

**Comment by ZhijieZhang** [comment] 2019-11-07 20:24
Hmm I think the fix I made for https://github.com/PDFTron/webviewer-ui/issues/400 also fixed this issue. I just tried and I couldn't reproduce it anymore.

I'm going to add a `stage: pending release` tag, which means the fix has been made and will be available in the next version! :)

**Comment by ZhijieZhang** [comment] 2019-11-07 23:19
Due to another fix we need to include in the official change I've also picked this one to our internal codebase. This means this fix will be available in the nightly build tomorrow. You can try out the build at https://www.pdftron.com/nightly/

Click stable -> click the latest date -> scroll to the bottom -> download WebViewer_5.2.8.xxxx.

Let me know how things go and if you have further questions! Thanks!

**Comment by Camo30** [comment] 2019-11-08 11:06
Same here, I tried it with the nightly from this morning and it's fixed 👍 thank you!

**Comment by ZhijieZhang** [comment] 2019-11-08 18:33
Thanks for confirming! Glad it works now.

I will close this issue and the other one you opened as there're no further actions needed now. :)

**Closed by ZhijieZhang** 2019-11-08 18:33 UTC
Labels: stage: pending release
