### ISSUE TITLE
Network error dialog does not dismiss

### ISSUE THREAD

**Issue by glendaviesnzdiligent** [PDFTron/webviewer-ui#160] opened 2019-02-13 00:01 UTC
In v1.1.0 the network error dialog does not dismiss, either with subsequent page load request, or clicking outside the dialog, a page refresh is needed to get rid of it. 

If you get the network error dialog it is possible to load another document into the viewer, and this loads successfully and can be seen behind the error overly. Ideally a successful new document load should dismiss the error dialog.

Thanks

**Comment by ZhijieZhang** [comment] 2019-02-13 18:23
Hi there,

Unfortunately we were not able to reproduce the issue you are seeing. Here are the steps we took:
1. Checkout master branch and run `npm start`
2. Open developer tools and in the console, run 
```javascript
readerControl.loadDocument('http://www.derpreport.com/wp-content/uploads/2017/02/GAA_Book.pdf')
```

3. Error dialog pops up showing: Network failure
4. In the console, load another document:
```javascript
readerControl.loadDocument('https://pdftron.s3.amazonaws.com/downloads/pl/webviewer-demo-annotated.pdf')
```
5. The above document loads successfully and the error dialog disappeared

We think this issue should be fixed in commit https://github.com/PDFTron/webviewer-ui/commit/b30a17ee626a2502c58fcd0e2db7c0cb1888bf0e.
If you try the steps above, are you still able to reproduce this issue? If yes, could you please provide us with the steps to reproduce it? 

Thanks

**Comment by justinjung04** [comment] 2019-06-14 21:04
We will close this issue due to inactivity. Feel free to reopen it if needed!

**Closed by justinjung04** 2019-06-14 21:04 UTC
