### ISSUE TITLE
Print issue

### ISSUE THREAD

**Issue by shmarlya** [PDFTron/webviewer-ui#348] opened 2019-09-05 15:37 UTC
WebViewer UI version: 5.1.7, WebViewer Core version: 5.1.7.71369

WebViewer(...)
  .then(function(instance) {
    var docViewer = instance.docViewer;

    // you must have a document loaded when calling this api
    docViewer.on('documentLoaded', function() {
      instance.print();
    });
  });

also provide webviewer settings
`    const opts: any = {
      path: '../lib',
      disabledElements: [
        'notesPanel', 'notesPanelButton', 'outlinesPanel', 'outlinesPanelButton',
        'contextMenuPopup', 'annotationStylePopup', 'textPopup'
      ],
      fullAPI: true,
      initialDoc: '../../files/webviewer-demo-annotated.pdf',
      pdfBackend: 'ems'
    };
`

Once i got called `instance.print();`
after that i made i change styles for parent element of viewerElement to `display:none`,
once i removed display:none, method called instantly

**Comment by ZhijieZhang** [comment] 2019-09-05 23:44
Thanks for bringing this up. 

I'm able to reproduce the issue and I'm suspecting this has something to do with the `<embed>` element. By default we use `<embed>` to handle PDF printing in Chrome. We found that the element will trigger the printing under some situations. One is toggling full screen though it's fixed now.

I'm not sure how to fix the `display:none` case though because the UI doesn't have control over how other apps are showing/hiding it. Maybe use a MutationObserver...?

There's an API you can call to remove `<embed>` and use the UI's default printing.
```javascript
instance.useEmbeddedPrint(false);
```

I can verify this fixes the issue. Let me know if you are okay with this.

**Comment by shmarlya** [comment] 2019-09-06 14:13
@ZhijieZhang  thanks for help,
yes, your solution fixes the problem, but it has one more additional pop up window, thats works as expected, before native print window appear.

**Comment by ZhijieZhang** [comment] 2019-09-09 17:45
Yes `instance.useEmbeddedPrint(false);` will make printing in Chrome behave the same as other browsers so it's expected there's one more additional popup window.

Seems to me that the issue is resolved so I will close it for now. Please feel free to reopen it if you find any issues or have further questions. Thanks!

**Closed by ZhijieZhang** 2019-09-09 17:45 UTC
